"""user profile

Revision ID: 2778bba27aa6
Revises: 2e7cd6991dfe
Create Date: 2015-03-18 15:55:24.887620

"""

# revision identifiers, used by Alembic.
revision = '2778bba27aa6'
down_revision = '2e7cd6991dfe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
