"""initial migration

Revision ID: 7d808f8c4d5
Revises: None
Create Date: 2015-03-08 22:17:07.229712

"""

# revision identifiers, used by Alembic.
revision = '7d808f8c4d5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
