"""empty message

Revision ID: ac68ea05356
Revises: 51b5ad39a79b
Create Date: 2015-03-13 15:49:25.854382

"""

# revision identifiers, used by Alembic.
revision = 'ac68ea05356'
down_revision = '51b5ad39a79b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
